name: Restaurante CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: |
          pytest tests/

      - name: Analizar calidad
        run: |
          flake8 app/

      - name: Escaneo de seguridad
        run: |
          bandit -r app/

      - name: Construir Docker
        run: |
          docker build -t restaurante-app .

      - name: Simular Deploy
        run: |
          echo "Deploy exitoso en Railway"